# Machine learning in bioinformatics

Dataset: a set of DNA sequences labeled with 0 and 1

Aim: build a classifier that will predict the label for new DNA sequences

ML workflow:

- import the dataset
- prepare ML method(s) and encoding(s) and the set of hyperparameters to be evaluated
- set up the evaluation of methods and encodings
- select the final model

## Importing the data

The data is located in data.fa file. For each sequence, there is a line starting with `>` with the sequence label (0 or 1), and a new line with the DNA sequence itself:
```
> 1
AGCGAGGCAGGTGCGGTCACGTGACCCGGCGGCGCTGCGGGGCAGCGGCCATTTTGCGGGGCGGCC
> 0
AGCGAGGGCGCTCGGAGTGCGACGTTTTGGCACCAGGCGGGGCGCACGGCATTGCCAAGCGGCCGC
```

Function load_data will import this data into a pandas dataframe.

In [1]:
from util import load_data

dataset = load_data("data.fa")

dataset.head(10)

sequence  label
0  AGCGAGGCAGGTGCGGTCACGTGACCCGGCGGCGCTGCGGGGCAGC...      1
1  AGCGAGGGCGCTCGGAGTGCGACGTTTTGGCACCAGGCGGGGCGCA...      0
2  TCTGGTCCCACTTAGCGGGAGAAACTCGGGCCACGTGACTGTCTGA...      1
3  TCGCGTCTCCTGCCTCCCTGTCCCGGGGCGAGGACTGTCTCAGAAA...      0
4  ACTCCCCAGGTCAGCTGACGCTGCGTCCTCAGCGGGCTGTCAAGTG...      1
5  AGAAGAACTCGGGGCTGGAACCTGTCGTACGGGTGTCCAGCAGCTG...      0
6  GCTGGGAGGCGGTCACGTGGCGCAGGATGCACCCAACACCACCGTC...      1
7  GCCGCAGTCGGGCCCAGTGGATGGCGCACTCGACGGGAACCCGCGT...      0
8  TGAAGCCGCCATTTCCCCGGCCCAGCCACCACGTGACCCTTCTGCG...      1
9  TCCCGGCGAGCACGGACATACCCCATAGCTTTCTCCTCCGCCCGTG...      0

## Defining ML methods and encodings

In this section, a few ML methods will be defined. You can use any other suitable ML method from scikit-learn library that is already installed in this environment.

In [4]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

from util import encode_onehot


# ML methods - defining ML methods to be used

logistic_regression = LogisticRegression()
random_forest = RandomForestClassifier()

# encodings - encodes the data right away and returns a dictionary with encoded_data, labels, and feature_names

one_hot_encoding = encode_onehot(dataset)

print(one_hot_encoding['encoded_data'])

[[1. 0. 0. ... 0. 0. 1.]
 [1. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 1. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]]


### Defining a custom encoding

Another encoding that can be used in this setting is based on the frequency of subsequences within a sequence.

For example, if the original sequence is `AGCGAG`, subsequences of length 3 (3-mers) are:
- `AGC`
- `GCG`
- `CGA`
- `GAG`.

The encoding would then represent each sequence by the frequency of each possible 3-mer. For sequence `AGCGAG` it would be:

```
[0., 0., 0., 0., 0., 0., 0., 0., 0, 0.25, 0.,
 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
 0., 0., 0.25, 0., 0., 0., 0., 0., 0., 0., 0.,
 0., 0.25, 0., 0., 0., 0.25, 0., 0., 0., 0., 0.,
 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
 0., 0., 0., 0., 0., 0., 0., 0., 0.]
```

The first number is then the frequency of 3-mer `AAA`, the second the frequency of `AAC`, third `AAG`, ..., and the last one is the frequency of `TTT`.

Here you can implement the function that will encode the dataset by representing each DNA sequence by the frequency of its subsequences.

The function should take a pandas DataFrame as input with columns `sequence` and `label` (as shown above). It should output a dictionary with the following keys: `encoded_data` (matrix where each row represents one sequence and each column represents the frequency of one k-mer), `labels` (an array of labels for each sequence), and `feature_names` (a list of features names, e.g., `AAA`, `AAC`, `ACA`, etc.)

In [5]:
import pandas as pd
from util import ALPHABET

# all letters (nucleotides) that can be used in a sequence:
print(ALPHABET)

# define a custom encoding:

def encode_kmer_frequencies(dataset: pd.DataFrame, k: int) -> dict:
    
    # add your code here and fill in the returned object
    
    return {
        'encoded_data': None,
        'labels': None,
        'feature_names': None
    }

['A', 'C', 'G', 'T']


In [4]:
import numpy as np
from util import test_kmer_encoding

test_kmer_encoding(encode_kmer_frequencies_func=encode_kmer_frequencies)
    

k-mer encoding works!
